import type { Metadata } from "next";
import { Providers } from "@/providers/providers";
import BottomTabs from "@/components/common/BottomTabs";
import "./global.scss";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/grid';

export const metadata: Metadata = {
  title: "Ecommerce Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Providers>
            <div className="content">
              {children}
            </div>
            <BottomTabs />
          </Providers>
        </main>
      </body>
    </html>
  );
}
